# Nelder–Mead method

## v5 
$(x1+10x2)^2 + 5(x3-x4)^2 + (x2-2x3)^4 + 10(x1-x4)^4$
; x0 = [3;-1;0;1]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def f(x):
    return (x[0]+10*x[1])**2 + 5*(x[2]-x[3])**2 + (x[1]-2*x[2])**4 + 10*(x[0]-x[3])**4

In [32]:
def Nelder_Mead(x0=[3, -1, 0, 1], end=1000, delta=10**(-20)):
    alfa = 1
    beta = 0.5
    gamma = 2
    min_start = 10

    # check correct
    if check(x0, end, delta):
        return 0
    x0 = np.array(x0, dtype=float)

    # init val
    x1, x2, x3, x4 = x0.copy(), x0.copy(), x0.copy(), x0.copy()
    x1[0] += 1
    x2[1] += 1
    x3[2] += 1
    x4[3] += 1
    x = np.array([x0, x1, x2, x3, x4])
    y = np.array([f(x0), f(x1), f(x2), f(x3), f(x4)])

    # SORT ARRAY OF VALUES
    index = np.argsort(y)
    x = x[index]
    y = y[index]
    print('before ------------')
    print('y=', y, 'x=', x)

    i = 0
    while i < end and np.std(y) > delta:
        # b-best, g-good, w-worst
        f_w, x_w = y[-1], x[-1]
        f_b, x_b = y[0], x[0]
        f_g, g_g = y[-2], x[-2]

        x_c = np.mean(x[:-1], axis=0)
        x_r = (1 + alfa) * x_c - alfa * x_w
        f_r = f(x_r)
        if f_r < f_b:
            x_e = x_c + gamma * (x_r - x_c)

            if f(x_e) < f_r:
                x = np.insert(x[:-1], 0, x_e, axis=0)
                y = np.insert(y[:-1], 0, f(x_e), axis=0)
            else:
                x = np.insert(x[:-1], 0, x_r, axis=0)
                y = np.insert(y[:-1], 0, f_r, axis=0)

        elif f_b < f_r < f_g:
            x = np.insert(x[:-1], 1, x_r, axis=0)
            y = np.insert(y[:-1], 1, f_r, axis=0)

        elif f_g < f_r:
            x_s = beta * x_w + (1 - beta) * x_c
            f_s = f(x_s)
            if f_s < f_w:
                x = np.insert(x[:-1], 0, x_s, axis=0)
                y = np.insert(y[:-1], 0, f_s, axis=0)
                index = np.argsort(y)
                x = x[index]
                y = y[index]
            else:
                x = np.array([x_b + (xi - x_b) / 2 if xi.all() != x_b.all() else x_b for xi in x])
                y = np.array([f(x[0]), f(x[1]), f(x[2]), f(x[3]), f(x[4])])
                index = np.argsort(y)
                x = x[index]
                y = y[index]
        i += 1
    print('after ------------')
    print('y=', y, 'x=', x)
    print(f'\n\n min_f={y[0]}, min_x={x[0]}')


In [33]:
def check(x, end, delta):
    for xi in x:
        if type(xi) is not int and type(xi) is not float:
            print('type x0 must int or float')
            return 1 
        if -100 > xi or xi > 100:
            print('x0 must be between interval [-100, 100]')
            return 1
    
    if type(delta) is not int and type(delta) is not float:
        print('type delta must int or float')
        return 1
    
    if type(end) is not int:
        print('type end must int')
        return 1
    
    if  -100 > delta or delta > 100:
        print('delta must be between interval [-100, 100]')
        return 1
    
    if 0 > end or end >= 1000:
        print('end must be lower 1000 and more than 0')
        return 1
    
    return 0

In [34]:
Nelder_Mead(end=500)

before ------------
y= [ 80. 174. 215. 290. 852.] x= [[ 3. -1.  0.  2.]
 [ 3.  0.  0.  1.]
 [ 3. -1.  0.  1.]
 [ 3. -1.  1.  1.]
 [ 4. -1.  0.  1.]]
after ------------
y= [3.15890095e-20 3.24659601e-20 3.39055957e-20 4.17367594e-20
 4.62165132e-20] x= [[-5.74224425e-06  5.74219108e-07 -4.68404174e-06 -4.68410334e-06]
 [-9.59280557e-06  9.59284619e-07 -5.83726278e-06 -5.83723689e-06]
 [ 2.37311545e-06 -2.37316228e-07 -4.66794812e-06 -4.66794062e-06]
 [-6.03804979e-06  6.03790388e-07 -5.50546971e-06 -5.50549090e-06]
 [-4.01638843e-06  4.01642360e-07 -6.24578577e-06 -6.24584425e-06]]


 min_f=3.158900950306943e-20, min_x=[-5.74224425e-06  5.74219108e-07 -4.68404174e-06 -4.68410334e-06]


In [27]:
Nelder_Mead(x0=[1,1,1,1], end=-1, delta=0.1)

Nelder_Mead(x0=[1,1,1,1], end=1, delta=-101)

Nelder_Mead(x0=[1,1,1,1], end=1, delta=101)

Nelder_Mead(x0=[1,1,1,101], end=1, delta=0.1)

end must be lower 1000 and more than 0
delta must be between interval [-100, 100]
delta must be between interval [-100, 100]
x0 must be between interval [-100, 100]


0