# Лабораторна робота № 1 СЛАР: 

## 7– Метод оберної матриці

In [1]:
import numpy as np
import pandas as pd

## v8

2*x1 - x2 + x3 + 2*x4 = 5

x1 + 2*x2 +2*x3 - x4 = 3

2*x1 - 3*x2 + 2*x3 - 2*x4 = 2

3*x1 + 3*x2 - 2*x3 + 4*x4 = 5


### 1) download data from csv

In [6]:
data = pd.read_csv('system.csv')

### 2) create function for check the download data for uncorrect data

In [3]:
def check_data(data_pd): 
    
    if len(data_pd.columns)-1 != len(data_pd.index):
        print('uncorrect count of colunms and rows')
        return 0
    
    for column in data_pd.columns:
        if data_pd[column].dtype != np.float64 and data_pd[column].dtype != np.int64:
            print('uncorrect data type({}) of column "{}"'.format(data_pd[column].dtype, column))
            return 0
        
    if pd.isna(data_pd).values.any():
        print('uncorrect data value of df is NaN')
        return 0
    
    if (data_pd > 9999).values.any():
        print('uncorrect data value of df more then 9999')
        return 0
    
    return 1

### 3) create method function 

In [11]:
def method(data_pd):
    
    # check uncorrect situations
    A = data_pd.iloc[:, :-1]
    y = data_pd.iloc[:, -1]

    if A.shape[0] != A.shape[1]:
        print('error, shape of x should be quadratic')
        return 0

    det = np.linalg.det(A)
    if det == 0:
        print('error, det shuld be not 0')
        return 0
    
    print("A = \n", A)
    inv_A = np.linalg.inv(A)
    print("inverse A = \n", inv_A)
    x = np.dot(inv_A, y)
    
    return x


### 4) run check and method functions and print answer

In [12]:
if check_data(data):
    answer = method(data)
    if type(answer) is not int:
        answer_str = " = {}; \n".join(data.columns)[:-1]
        print('answer is: \n' + answer_str.format(*answer))

A = 
    x1  x2  x3  x4
0   2  -1   1   2
1   1   2   3  -1
2   2  -3   2  -2
3   3   3  -2   4
inverse A = 
 [[-0.16774194  0.01290323  0.30322581  0.23870968]
 [-0.18064516  0.16774194 -0.05806452  0.10322581]
 [ 0.31612903  0.20645161 -0.1483871  -0.18064516]
 [ 0.41935484 -0.03225806 -0.25806452 -0.09677419]]
answer is: 
x1 = 0.9999999999999999; 
x2 = 0.0; 
x3 = 1.0000000000000004; 
x4 = 0.9999999999999998; 



### 5) analize difference between my answer and insert fucntion answer

In [10]:
np_pr = np.linalg.solve(data.iloc[:, :-1], data.iloc[:, -1])
print('numpy predict is: \n' + answer_str.format(*np_pr))

print('difference:')
for x_1, x_2 in zip(answer, np_pr):
    print('|my_x - x_pr| =', abs(x_1 - x_2))

numpy predict is: 
x1 = 1.0000000000000002; 
x2 = -0.0; 
x3 = 0.9999999999999998; 
x4 = 0.9999999999999998; 

difference:
|my_x - x_pr| = 3.3306690738754696e-16
|my_x - x_pr| = 0.0
|my_x - x_pr| = 6.661338147750939e-16
|my_x - x_pr| = 0.0
