# Nelder–Mead method

## v5 
$(x1+10x2)^2 + 5(x3-x4)^2 + (x2-2x3)^4 + 10(x1-x4)^4$
; x0 = [3;-1;0;1]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
def f(x):
    return (x[0]+10*x[1])**2 + 5*(x[2]-x[3])**2 + (x[1]-2*x[2])**4 + 10*(x[0]-x[3])**4

In [72]:
def Nelder_Mead(x0=[3, -1, 0 , 1], end=1000):

    alfa = 1
    beta = 0.5
    gamma = 2
    
    #check correct
    x0 = np.array(x0, dtype=float)
    
    # init val
    x1,x2,x3,x4 = x0.copy(), x0.copy(), x0.copy(), x0.copy()
    x1[0] += 1
    x2[1] += 1
    x3[2] += 1
    x4[3] += 1
    x = np.array([x0,x1,x2,x3,x4])
    y = np.array([f(x0), f(x1), f(x2) ,f(x3), f(x4)])

    # SORT ARRAY OF VALUES
    index = np.argsort(y)
    x = x[index]
    y = y[index]
    print('before ------------')
    print('y=', y, 'x=', x)
    
    i = 0
    while i<end:
        # b-best, g-good, w-worst
        f_w, x_w = y[-1], x[-1]
        f_b, x_b = y[0], x[0]
        f_g, g_g = y[-2], x[-2]
        
        x_c = np.mean(x[:-1], axis=0)
        x_r = (1 + alfa) * x_c - alfa * x_w
        f_r = f(x_r)
        if f_r < f_b:
            x_e = x_c + gamma*(x_r-x_c)
            
            if f(x_e) < f_r:
                x = np.insert(x[:-1], 0, x_e, axis=0)
                y = np.insert(y[:-1], 0, f(x_e), axis=0)
            else:
                x = np.insert(x[:-1], 0, x_r, axis=0)
                y = np.insert(y[:-1], 0, f_r, axis=0)
                
        elif f_b < f_r < f_g :
            x = np.insert(x[:-1], 1, x_r, axis=0)
            y = np.insert(y[:-1], 1, f_r, axis=0)
            
        elif f_g < f_r :
            x_s = beta * x_w + (1 - beta) * x_c
            f_s = f(x_s)
            if f_s < f_w:
                x = np.insert(x[:-1], 0, x_s, axis=0)
                y = np.insert(y[:-1], 0, f_s, axis=0)
                index = np.argsort(y)
                x = x[index]
                y = y[index]
            else:
                x = [x_b + (xi - x_b)/2 if xi != x_b else x_b for xi in x ]
                y = [f(x0), f(x1), f(x2) ,f(x3), f(x4)]
                index =np.argsort(y)
                x = x[index]
                y = y[index]        
        i+=1
    print('after ------------')
    print('y=', y, 'x=', x)

In [73]:
Nelder_Mead(end=500)

before ------------
y= [ 80. 174. 215. 290. 852.] x= [[ 3. -1.  0.  2.]
 [ 3.  0.  0.  1.]
 [ 3. -1.  0.  1.]
 [ 3. -1.  1.  1.]
 [ 4. -1.  0.  1.]]
after ------------
y= [3.61735849e-35 3.61898208e-35 4.24161812e-35 4.82307528e-35
 5.05221834e-35] x= [[ 1.02403454e-09 -1.02403454e-10 -2.30328919e-10 -2.30328921e-10]
 [ 8.02593617e-10 -8.02593619e-11 -5.26957720e-10 -5.26957720e-10]
 [ 9.04259521e-10 -9.04259521e-11 -4.31762899e-10 -4.31762897e-10]
 [ 9.26568455e-10 -9.26568453e-11 -4.98736211e-10 -4.98736210e-10]
 [ 1.50681141e-09 -1.50681141e-10  7.35837049e-11  7.35837038e-11]]


In [57]:
Nelder_Mead(end=10000)

before ------------
y= [ 80 174 215 290 852] x= [[ 3 -1  0  2]
 [ 3  0  0  1]
 [ 3 -1  0  1]
 [ 3 -1  1  1]
 [ 4 -1  0  1]]
after ------------
y= [19 32 74 63 80] x= [[ 2  0  0  1]
 [ 1  0  0  1]
 [ 2  0  0  1]
 [ 2  0 -1  1]
 [ 3 -1  0  2]]
